window.PARTS = [
  { id: "Transducers & RTD", color: "cyan", qs: "Q1–5" },
  { id: "Pressure", color: "blue", qs: "Q6–10" },
  { id: "Electro-mechanical", color: "purple", qs: "Q11–16" },
  { id: "Resistive pressure", color: "orange", qs: "Q17–20" },
  { id: "Capacitive pressure", color: "yellow", qs: "Q21–24" },
  { id: "Ultrasonic flow", color: "green", qs: "Q25–26" },
  { id: "Liquid level", color: "cyan", qs: "Q27–29" },
  { id: "Signal conditioning", color: "pink", qs: "Q30–32" },
  { id: "Amplifiers", color: "blue", qs: "Q33–36" },
  { id: "Op-amp", color: "purple", qs: "Q37–40" },
  { id: "Instrumentation amp", color: "cyan", qs: "Q41–44" },
  { id: "Noise", color: "red", qs: "Q45–51" },
  { id: "ADC", color: "orange", qs: "Q52–60" }
];

window.QUESTIONS = [
  { n:1, part:"Transducers & RTD", title:"Transduction and transducer", core:false, fig:"transducer",
    defs:[["Transduction","Converting one form of energy into another form."],["Transducer","A device that converts a physical quantity into a usable electrical signal."]],
    points:["Easy to measure and process.","Can transmit signals over long distances.","More accurate and sensitive."],
    example:"A temperature sensor converts temperature into an electrical signal." },
  { n:2, part:"Transducers & RTD", title:"Primary vs secondary transducer", core:false, fig:"primary",
    table:{ headers:["Primary transducer","Secondary transducer"], rows:[["Directly senses the physical quantity.","Converts the primary output into an electrical signal."],["Usually produces mechanical displacement.","Usually produces an electrical output."]] },
    example:"Bourdon tube is primary; strain gauge is secondary." },
  { n:3, part:"Transducers & RTD", title:"Working principle of RTD and PTC", core:true, fig:"rtd",
    defs:[["RTD","Resistance Temperature Detector. Metal resistance changes with temperature."],["PTC","Positive Temperature Coefficient: temperature up, resistance up."]],
    formula:"Temperature ↑  →  Resistance ↑", example:"Platinum RTD." },
  { n:4, part:"Transducers & RTD", title:"Three characteristics of a good RTD material", core:false,
    points:["High temperature coefficient — resistance changes noticeably with temperature.","Stable properties — gives reliable readings.","High resistivity — allows a practical sensor size."],
    example:"Platinum is commonly used in RTDs." },
  { n:5, part:"Transducers & RTD", title:"Thermistor vs metal RTD", core:false,
    defs:[["Thermistor","A temperature-sensitive resistor made mainly from semiconductor materials."]],
    table:{ headers:["Thermistor","Metal RTD"], rows:[["Usually semiconductor","Usually metal"],["Very high sensitivity","Lower sensitivity"],["Smaller in size","Larger"],["Usually NTC","Usually PTC"]] },
    example:"NTC thermistor is used in temperature sensors." },
  { n:6, part:"Pressure", title:"What is pressure?", core:true, fig:"pressure",
    defs:[["Pressure","Force acting normally on a unit area."]], formula:"P = F / A    (F = force, A = area)", example:"Air pressure inside a tire." },
  { n:7, part:"Pressure", title:"Absolute pressure", core:true, fig:"pressure-types",
    defs:[["Absolute pressure","Pressure measured with respect to a perfect vacuum."]], formula:"P_abs = P_atm + P_g",
    example:"If P_atm = 100 kPa and P_g = 50 kPa, then P_abs = 150 kPa." },
  { n:8, part:"Pressure", title:"Gauge pressure", core:true, fig:"pressure-types",
    defs:[["Gauge pressure","Pressure measured relative to atmospheric pressure."]], formula:"P_g = P_abs − P_atm",
    example:"A car tire pressure gauge shows gauge pressure." },
  { n:9, part:"Pressure", title:"Differential pressure", core:true, fig:"diff-p",
    defs:[["Differential pressure","The difference between two pressures."]], formula:"P_d = P1 − P2",
    example:"Pressure difference between two points of a pipe." },
  { n:10, part:"Pressure", title:"Absolute, gauge and differential pressure", core:true, fig:"pressure-types",
    table:{ headers:["Type","Reference"], rows:[["Absolute pressure","Perfect vacuum"],["Gauge pressure","Atmospheric pressure"],["Differential pressure","Another pressure"]] },
    example:"Tire pressure is usually measured as gauge pressure." },
  { n:11, part:"Electro-mechanical", title:"Electro-mechanical pressure measurement systems", core:false, fig:"emech",
    defs:[["Definition","Systems that convert pressure into an electrical signal using mechanical movement and an electrical transducer."]],
    formula:"Pressure → diaphragm movement → electrical voltage", example:"Industrial pressure transmitters." },
  { n:12, part:"Electro-mechanical", title:"Two main elements", core:false,
    points:["Sensing element","Secondary transducer"], example:"Diaphragm + strain gauge." },
  { n:13, part:"Electro-mechanical", title:"Sensing element", core:false,
    defs:[["Sensing element","The part that directly detects the physical quantity and responds to it."]],
    example:"A diaphragm bends when pressure is applied." },
  { n:14, part:"Electro-mechanical", title:"Secondary transducer", core:false,
    defs:[["Secondary transducer","Converts the mechanical output of the sensing element into an electrical signal."]],
    example:"Strain gauge converts diaphragm deformation into a resistance change." },
  { n:15, part:"Electro-mechanical", title:"Why are they called secondary transducers?", core:false,
    defs:[["Why secondary","They do not directly sense the physical quantity. They receive mechanical output from the primary sensing element and convert it into an electrical signal."]] },
  { n:16, part:"Electro-mechanical", title:"Working principle", core:false, fig:"emech",
    formula:"Pressure → sensing element moves/deforms → secondary transducer → electrical signal",
    example:"Pressure → diaphragm bends → strain gauge resistance changes → voltage changes." },
  { n:17, part:"Resistive pressure", title:"How does a strain gauge work?", core:true, fig:"strain",
    defs:[["Strain gauge","Its electrical resistance changes when it is stretched or compressed."]],
    formula:"Strain → resistance change",
    example:"When a diaphragm bends, the attached strain gauge stretches and its resistance changes." },
  { n:18, part:"Resistive pressure", title:"Why is silicon commonly used?", core:false,
    points:["High sensitivity to strain","Small size","Good electrical properties"],
    example:"Silicon strain gauges can detect very small pressure changes." },
  { n:19, part:"Resistive pressure", title:"Identify a resistive pressure transducer", core:false,
    defs:[["Answer","A strain-gauge pressure transducer."]], formula:"Pressure → mechanical strain → resistance change" },
  { n:20, part:"Resistive pressure", title:"Disadvantages of resistive pressure sensors", core:false,
    points:["Temperature can affect resistance.","Requires electrical power.","Resistance changes can be small."],
    example:"Temperature changes may cause measurement errors." },
  { n:21, part:"Capacitive pressure", title:"Working principle of capacitive pressure transducers", core:true, fig:"cap",
    defs:[["Principle","Capacitance changes when pressure changes the distance between capacitor plates."]],
    formula:"C = εA / d     If d decreases → C increases", example:"Pressure bends a diaphragm toward a fixed plate." },
  { n:22, part:"Capacitive pressure", title:"Diaphragm-based capacitive sensor", core:false, fig:"cap",
    defs:[["Construction","A flexible diaphragm and a fixed plate. Pressure moves the diaphragm, changing plate distance and therefore capacitance."]] },
  { n:23, part:"Capacitive pressure", title:"Single vs differential capacitor", core:false, fig:"cap-diff",
    defs:[["Single","Uses one variable capacitor."],["Differential","Uses two capacitors; when one capacitance increases, the other decreases."]],
    points:["Advantage of differential design: better sensitivity and reduced errors."] },
  { n:24, part:"Capacitive pressure", title:"Why are capacitive sensors highly accurate?", core:false,
    points:["They can detect very small changes in displacement.","High sensitivity","Low mechanical movement","Good resolution"] },
  { n:25, part:"Ultrasonic flow", title:"Working principle of an ultrasonic flowmeter", core:true, fig:"flow",
    defs:[["Principle","Uses ultrasonic sound waves. The time difference between upstream and downstream travel gives flow velocity."]],
    example:"Faster downstream travel indicates faster fluid flow." },
  { n:26, part:"Ultrasonic flow", title:"Construction, advantages and limitations", core:false,
    points:["Construction: ultrasonic transmitters, receivers, and a flow pipe.","Advantages: no moving parts; no obstruction; can measure many liquids.","Limitations: more expensive; bubbles or particles can affect performance."] },
  { n:27, part:"Liquid level", title:"Time-of-flight method", core:false, fig:"level",
    defs:[["TOF","Measures the time taken by an ultrasonic signal to travel from the sensor to the liquid surface and return."]],
    example:"Sensor sends sound → sound reflects from water → sensor receives echo." },
  { n:28, part:"Liquid level", title:"Distance calculation", core:false, fig:"level",
    formula:"d = v t / 2     d = distance, v = speed of sound, t = round-trip time",
    points:["Divide by 2 because the sound travels to the surface and back."] },
  { n:29, part:"Liquid level", title:"Ultrasonic level measurement", core:false, fig:"level",
    points:["Sensor sends sound waves toward the liquid surface.","Reflected wave returns; time is measured.","Distance is used to calculate liquid level."],
    formula:"d = v t / 2" },
  { n:30, part:"Signal conditioning", title:"What is signal conditioning?", core:true, fig:"condition",
    defs:[["Signal conditioning","Modifying a sensor's output so it becomes suitable for measurement or processing."]],
    example:"Amplifying a weak sensor signal." },
  { n:31, part:"Signal conditioning", title:"Why is signal conditioning necessary?", core:true,
    points:["Increase signal strength.","Remove noise.","Convert the signal into a suitable form."],
    example:"A weak sensor voltage is amplified before sending it to an ADC." },
  { n:32, part:"Signal conditioning", title:"Main processes of signal conditioning", core:true,
    points:["Amplification — increases signal strength.","Filtering — removes unwanted noise.","Conversion — changes signal into a suitable form.","Isolation — protects circuits."] },
  { n:33, part:"Amplifiers", title:"What is an amplifier?", core:true, fig:"amp",
    defs:[["Amplifier","An electronic circuit that increases the amplitude or strength of a signal."]],
    example:"Increasing a 0.1 V sensor signal to 1 V." },
  { n:34, part:"Amplifiers", title:"High input and low output impedance", core:true, fig:"z",
    defs:[["High input impedance","Prevents the amplifier from drawing significant current from the sensor."],["Low output impedance","Allows the amplifier to deliver the signal effectively to the next circuit."]],
    points:["High input impedance → does not disturb sensor.","Low output impedance → easily drives next circuit."] },
  { n:35, part:"Amplifiers", title:"Why are amplifiers needed in instrumentation?", core:true,
    defs:[["Reason","Sensor signals are often very weak. Amplifiers raise them so they can be measured, processed, and sent to other circuits."]],
    example:"A sensor produces 10 mV; the amplifier increases it to 1 V." },
  { n:36, part:"Amplifiers", title:"Characteristics of a good amplifier", core:true,
    points:["High gain","High input impedance","Low output impedance","Low noise","Good stability"] },
  { n:37, part:"Op-amp", title:"What is an op-amp?", core:true, fig:"opamp",
    defs:[["Op-amp","A high-gain electronic amplifier with two inputs and one output, used for amplification and signal processing."]],
    example:"Used in amplifiers, filters and mathematical circuits." },
  { n:38, part:"Op-amp", title:"Open-loop gain", core:true,
    defs:[["Open-loop gain","Gain of an op-amp when no feedback is applied. It is usually very high."]], formula:"A_OL = V_out / V_in" },
  { n:39, part:"Op-amp", title:"Common-mode gain", core:true,
    defs:[["Common-mode gain","Gain of an amplifier for signals that are the same at both inputs. A good instrumentation amplifier has very low common-mode gain."]],
    formula:"A_CM = V_out / V_CM" },
  { n:40, part:"Op-amp", title:"Advantages of op-amps", core:true,
    points:["Very high gain","High input impedance","Low output impedance","Small size","Low cost"] },
  { n:41, part:"Instrumentation amp", title:"What is an instrumentation amplifier?", core:true, fig:"inamp",
    defs:[["Instrumentation amplifier","A precision amplifier designed to amplify small differential signals while rejecting common noise."]],
    example:"Used with temperature, pressure and strain sensors." },
  { n:42, part:"Instrumentation amp", title:"Why preferred in measurement systems?", core:true,
    points:["High accuracy","High input impedance","High common-mode rejection","Low noise"],
    example:"It can amplify a tiny sensor signal even when noise is present." },
  { n:43, part:"Instrumentation amp", title:"Gain equation", core:true,
    formula:"A_v = (1 + 2R / R_G) × (R3 / R2)     R_G controls the gain" },
  { n:44, part:"Instrumentation amp", title:"Advantages of instrumentation amplifier", core:true,
    points:["High input impedance","High CMRR","High accuracy","Low noise","Adjustable gain"] },
  { n:45, part:"Noise", title:"What is noise?", core:true, fig:"noise",
    defs:[["Noise","An unwanted electrical signal that interferes with the desired signal."]],
    example:"Electrical interference appearing in a sensor signal." },
  { n:46, part:"Noise", title:"Effect of noise on measurement", core:true,
    points:["Measurement errors","Unstable readings","Reduced accuracy"],
    example:"A sensor should read 10 V but noise makes the reading fluctuate between 9.8–10.2 V." },
  { n:47, part:"Noise", title:"Define resolution", core:true,
    defs:[["Resolution","The smallest change in a quantity that a measuring system can detect."]],
    example:"A thermometer with 0.1 °C resolution can detect a 0.1 °C change." },
  { n:48, part:"Noise", title:"Internal and external noise", core:true,
    defs:[["Internal noise","Generated inside the electronic device itself."],["External noise","Comes from outside the system."]],
    example:"Internal → thermal noise. External → electromagnetic interference from motors." },
  { n:49, part:"Noise", title:"Thermal noise", core:true,
    defs:[["Thermal noise","Noise caused by the random movement of electrons due to temperature. Also called Johnson noise."]],
    example:"Resistors produce thermal noise." },
  { n:50, part:"Noise", title:"Shot noise", core:true,
    defs:[["Shot noise","Caused by the random movement of charge carriers in electronic devices. Common in semiconductors."]],
    example:"Current flowing through a diode produces shot noise." },
  { n:51, part:"Noise", title:"Pink noise", core:true,
    defs:[["Pink noise","Noise whose power decreases as frequency increases. Also called 1/f noise."]],
    formula:"P ∝ 1 / f", example:"It can occur in electronic circuits and sensors." },
  { n:52, part:"ADC", title:"What is an ADC?", core:true, fig:"adc",
    defs:[["ADC","Analog-to-Digital Converter. Converts an analog signal into a digital/binary signal."]],
    example:"Temperature sensor → analog voltage → ADC → binary data." },
  { n:53, part:"ADC", title:"Why is an ADC required?", core:true,
    defs:[["Reason","Computers and digital systems understand digital/binary data, so analog sensor signals must be converted."]],
    example:"Microphone signal → ADC → computer." },
  { n:54, part:"ADC", title:"Steps of analog-to-digital conversion", core:true, fig:"adc-steps",
    points:["Sampling — take measurements at regular time intervals.","Quantization — convert each sample to the nearest discrete level.","Encoding — convert the quantized level into binary code."],
    formula:"Analog signal → Sampling → Quantization → Encoding → Digital signal" },
  { n:55, part:"ADC", title:"What is sampling?", core:true, fig:"sample",
    defs:[["Sampling","Taking the value of an analog signal at regular time intervals."]],
    example:"Taking 1000 samples every second from a sound signal." },
  { n:56, part:"ADC", title:"Nyquist theorem", core:true, fig:"nyquist",
    defs:[["Nyquist","Sampling frequency must be at least twice the highest frequency of the signal."]],
    formula:"f_s ≥ 2 f_max", example:"If f_max = 5 kHz, then f_s ≥ 10 kHz." },
  { n:57, part:"ADC", title:"What is aliasing?", core:true, fig:"alias",
    defs:[["Aliasing","Occurs when a signal is sampled at less than twice its highest frequency. The sampled signal then appears as a wrong lower-frequency signal."]],
    example:"If f_max = 5 kHz, sampling below 10 kHz can cause aliasing." },
  { n:58, part:"ADC", title:"What is quantization?", core:true, fig:"quant",
    defs:[["Quantization","Converting sampled continuous values into a limited number of discrete levels."]],
    example:"A voltage of 2.13 V may be rounded to the nearest ADC level, such as 2.1 V." },
  { n:59, part:"ADC", title:"What is encoding?", core:true,
    defs:[["Encoding","Converting the quantized value into binary code."]], example:"Quantized level 5 → binary code 0101." },
  { n:60, part:"ADC", title:"How is binary code assigned in an ADC?", core:true, fig:"encode",
    defs:[["Assignment","The ADC divides the input voltage range into discrete levels. Each level gets a unique binary code."]],
    table:{ headers:["Level","Binary code"], rows:[["Level 0","00"],["Level 1","01"],["Level 2","10"],["Level 3","11"]] },
    example:"For a 2-bit ADC: 2² = 4 levels. Input is quantized, then the matching binary code is assigned." }
];
